// Generated by CoffeeScript 1.4.0
(function() {

  describe('Spaces', function() {
    return it('Não devem haver espaços globais duplicados', function() {
      var $spaces, ids;
      $spaces = $('.adlayer_global_space');
      ids = {};
      return $spaces.each(function() {
        ids[this.id] = ids[this.id] || 0;
        ids[this.id]++;
        return expect(ids[this.id]).to.be(1);
      });
    });
  });

}).call(this);
